pipeline {
    agent any

    stages{
        stage('Fetch Code'){
            steps{
                git branch: 'main', url: 'https://github.com/svishal16/demo-proj-mvn.git'
            }
        }
        stage('Generate Certificate'){
            steps{
                sh '''
                    keytool -genkeypair -alias domainname.com \
                        -keyalg RSA -keysize 2048 \
                        -dname "CN=domainname.com, OU=Devops, O=wiz4host, L=Jhansi, ST=UP, C=IN" \
                        -validity 3650 \
                        -keypass coti123pass \
                        -keystore mykeystore.jks \
                        -storepass coti123pass
                '''
                sh 'mv ./mykeystore.jks ./demo_proj_1_2/src/main/resources'
            }
        }

        // stage('Check application'){
        //     steps{
        //         sh 'curl -k https://localhost/api/hello'
        //     }
        // }
    }
}
