pipeline {
    agent any

    stages{
        stage('Generate Certificate'){
            steps{
                keytool -genkeypair -alias domainname.com \
                    -keyalg RSA -keysize 2048 \
                    -dname "CN=domainname.com, OU=Devops, O=wiz4host, L=Jhansi, ST=UP, C=IN" \
                    -validity 3650 \
                    -keypass coti123pass \
                    -keystore mykeystore.jks \
                    -storepass coti123pass
                mv ./mykeystore.jks ./src/main/resources
            }
        }

        stage('Check application'){
            steps{
                sh 'curl -k https://localhost/api/hello'
            }
        }
    }
}
