pipeline {
    agent any

    stages{
        stage('Fetch Code'){
            steps{
                git branch: 'main', url: 'https://github.com/svishal16/demo-proj-mvn.git'
            }
        }
        stage('Generate Certificate'){
            steps{
                sh '''
                    keytool -genkeypair -alias domainname.com \
                        -keyalg RSA -keysize 2048 \
                        -dname "CN=domainname.com, OU=Devops, O=wiz4host, L=Jhansi, ST=UP, C=IN" \
                        -validity 3650 \
                        -keypass coti123pass \
                        -keystore mykeystore.jks \
                        -storepass coti123pass
                '''
                sh 'mv ./mykeystore.jks ./demo_proj_1_2/src/main/resources'
            }
        }

        stage('Build Image'){
            steps{
                dir('demo_proj_1_2') {
                    sh 'mvn clean package -DskipTests'
                    sh 'docker build -t springboot-ssl-app .'
                    sh 'docker run -d -p 443:443 --name ssl-app springboot-ssl-app'
                }
            }
        }
        // stage('Check application'){
        //     steps{
        //         sh 'curl -k https://localhost/api/hello'
        //     }
        // }

        stage('Export Certificate'){
            steps{
                dir('demo_proj_1_2') {
                    sh ' keytool -export -alias domainname.com -file domainname.com.crt -keystore src/main/resources/mykeystore.jks -storepass coti123pass'
                }
            }
        }

    }
}
